/**
 * Offline lookup of Census place and county names by geoid.
 *
 * Replaces the runtime call to api.census.gov that `useJurisdictionName` used
 * to make. That endpoint began answering keyless requests with
 * `302 -> missing_key.html`, which the hook could only read as "no name", so
 * every city and county slice silently rendered its tab label ("City",
 * "County") instead of a place name.
 *
 * The data is generated by `scripts/generate-geo-names.mjs` from the Census
 * gazetteer and committed to `public/geo/`, one file per state. A member's city
 * and county geoids always share the state FIPS that prefixes them, so a single
 * shard answers every lookup that member will ever make — 8-30 KB over the wire
 * against ~300 KB for the national table.
 *
 * Run `npm run geo:check` to confirm the committed files still match the
 * gazetteer; `npm run geo:generate` to refresh them.
 */

export interface GeoName {
  /** Display-ready: place suffixes already stripped, county suffixes kept. */
  name: string
  /** Census internal point. Not used yet; here because the gazetteer carries it. */
  lat: number
  lon: number
  /**
   * 2020 Decennial total resident population (P1_001N).
   *
   * Absent for ~470 of 35,600 rows: small CDPs that the 2024 gazetteer lists
   * but the 2020 place enumeration does not, so there is genuinely no figure to
   * show. Callers must treat it as optional and render nothing when it is
   * missing, rather than a zero.
   */
  pop?: number
}

interface GeoShard {
  state: string
  names: Record<string, GeoName>
}

/**
 * state FIPS -> in-flight or settled shard load.
 *
 * Keyed on the promise rather than the value so that the six feed panels
 * mounting at once share one request instead of racing six.
 */
const shards = new Map<string, Promise<Record<string, GeoName> | null>>()

function loadShard(stateFips: string): Promise<Record<string, GeoName> | null> {
  const cached = shards.get(stateFips)
  if (cached) return cached

  const request = fetch(`${import.meta.env.BASE_URL}geo/${stateFips}.json`)
    .then(async (resp) => {
      if (!resp.ok) return null
      const shard = (await resp.json()) as GeoShard
      return shard.names ?? null
    })
    .catch(() => null)

  shards.set(stateFips, request)
  return request
}

/**
 * Resolves a geoid to its entry, or null if it is not a shape we carry.
 *
 * Four shapes resolve, all verified against the production slices table:
 *   7-digit place FIPS  "3702140" -> Asheville
 *   5-digit county FIPS "37021"   -> Buncombe County
 *   2-digit state FIPS  "37"      -> North Carolina
 *   the literal         "US"      -> United States of America
 *
 * Names for state and federal also resolve synchronously in
 * `geoidToDisplayName`, which is the cheaper path and stays the one the banner
 * title uses. This covers all four so that a caller wanting population —
 * which only lives here — does not need a second code path per level.
 *
 * The other sentinels are rejected by shape: "UNIFIED" is seven characters but
 * not numeric, and "VOLUNTEER" is nine. Neither is a place and neither has a
 * population.
 */
export async function lookupGeoName(geoid: string): Promise<GeoName | null> {
  const isNation = geoid === 'US'
  if (!isNation) {
    if (geoid.length !== 2 && geoid.length !== 5 && geoid.length !== 7) return null
    if (!/^\d+$/.test(geoid)) return null
  }

  const names = await loadShard(isNation ? 'us' : geoid.slice(0, 2))
  return names?.[geoid] ?? null
}
